# name: Run Eslint
# on: pull_request
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install modules
#         run: npm install
#       - name: Run ESLint
#         run: cd app && npx eslint . --ext .js,.jsx,.ts,.tsx

name: Linting
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd app && npm install
      - name: Run ESLint
        run: ./node_modules/eslint/bin/eslint.js . --ext .js,.jsx,.ts,.tsx
